### ISSUE TITLE
graphcore vs. petgraph?

### ISSUE THREAD

**Issue by alexreg** [metamolecular/gamma#1]
It would be nice if you could explain any advantages you see of your crate over the long-standing petgraph crate. (Or, is it just your own attempt for the sake of learning?)

**Comment by zimond** [comment]
there is an article comparing them https://depth-first.com/articles/2020/02/17/graphs-in-rust-introducting-graphcore/

**Comment by alexreg** [comment]
Okay, thank you! Definitely worth linking to in the README, I'd say.

**Comment by rapodaca** [comment]
@alexreg , @zimond is right. The readme will be updated.

**Comment by zimond** [comment]
This crate is very promising and I totally agree with what you said with the article. Is this any plans for directed graphs?

**Comment by rapodaca** [comment]
@zimond, there are no immediate plans for directed graphs, but `Graph` trait and `HashGraph` implementation should support it. Please feel free to create a separate issue.
