### ISSUE TITLE
Subgraph monomorphism/isomorphism?

### ISSUE THREAD

**Issue by j6k4m8** [metamolecular/gamma#5]
Is there an intention to add {iso|mono}-morphism graph matching to this library? I think the beginnings of graph-matching already exist here, but something for subgraph matching (i.e. Ullmann's or VF2) would be a hugely impactful addition.

References:

- [NetworkX implementation](https://github.com/networkx/networkx/pull/3435)
- [NetworkX documentation](https://networkx.github.io/documentation/networkx-2.2/reference/algorithms/isomorphism.vf2.html)
- [VF2 paper, Cordella et al 2004](http://ieeexplore.ieee.org/iel5/34/29305/01323804.pdf)

**Comment by rapodaca** [comment]
Yes, subgraph isomorphism is a must-have for the library I'm building  that uses Gamma. I don't have a timeframe, though.

I've implemented  VF2 a couple of times in other languages. I'm hoping to pull from that for Gamma, The work being done by NetworkX is also interesting.

The matching package in Gamma isn't related to isomorphism but rather matching in the sense of a graph whose nodes all have degree one.

What would be some applications you'd see for isomorphism support in Gamma?

**Comment by j6k4m8** [comment]
My biggest use-cases are node-induced-subgraph isomorphism and node-induced subgraph monomorphism; in particular, I'd love to use a speedy library like Gamma for some of the heavier lifting in [my team's brain-mapping research](https://bossdb.org/tools/DotMotif); I have plenty of other use-cases (pharma, in-memory graph-databases) that would also benefit a tremendous amount!

**Comment by rapodaca** [comment]
The plan is to implement subgraph isomorphism at some point.
