### ISSUE TITLE
Graph API nodes() should be an iterator?

### ISSUE THREAD

**Issue by skairunner** [metamolecular/gamma#8]
I am implementing a BTreeMap/Set-backed graph. I noticed that the nodes() method returns a slice of usize (`&[usize]`). This operation doesn't work very nicely for any graph that's not internally stored as a vector -- I imagine I would have to manually assemble a slice by iterating through the entire graph.  I wonder if nodes() should instead return an iterator of usize to allow for flexibility in implementations.

Existing code that uses nodes() as a slice can probably be trivially migrated by calling .collect() on the iterator.

Edit: Okay, so it looks like I rediscovered the reason why nodes() & edges() might not be an iterator -- no painless way to return a generic Iterator from trait methods because [Generic Associated Types](https://github.com/rust-lang/rust/issues/44265) isn't implemented yet. It still isn't very nice to return a slice from a usability perspective so I suppose I will poke around a bit and see if I can get some form of iterator working.

**Comment by skairunner** [comment]
I attempted changing only nodes() to be a boxed trait object Iterator. It seems like the changes are minimal enough that the gains in terms of ergonomics might be worth it. The diff is [here](https://github.com/metamolecular/gamma/compare/master...skairunner:iter?expand=1).

**Comment by rapodaca** [comment]
Thanks for the suggestion. Some simple benchmarks showed 10-20% slowdown using boxed iterators rather than slices. Gamma 0.9.0 implements the change in the `Graph` trait, which should increase the options for implementors of `Graph`.
